Lunch.create!([
  {date: "2016-01-04", entree: "Beef Stew ", month: "January", school_id: 1, description: nil, image: "beef_stew.jpg"},
  {date: "2016-01-05", entree: "Carnitas Burrito", month: nil, school_id: 1, description: nil, image: "burrito.jpg"},
  {date: "2016-01-06", entree: "Baked Pasta", month: nil, school_id: 1, description: nil, image: "baked_pasta.jpg"},
  {date: "2016-01-07", entree: "Sloppy Joes", month: nil, school_id: 1, description: nil, image: "sloppy_joes.jpg"},
  {date: "2016-01-08", entree: "Chicken Taco", month: nil, school_id: 1, description: nil, image: "taco.jpg"},
  {date: "2016-01-11", entree: "Ham & Cheese English Muffin", month: nil, school_id: 1, description: nil, image: "ham_cheese.jpg"},
  {date: "2016-01-12", entree: "Chicken Nuggets", month: nil, school_id: 1, description: nil, image: "chicken_nuggets.jpg"},
  {date: "2016-02-13", entree: "Ham & Cheese English Muffin", month: nil, school_id: 3, description: nil, image: "ham_cheese.jpg"},
  {date: "2016-02-14", entree: "Pesto Pasta with Garlic Cheese Bread", month: nil, school_id: 1, description: nil, image: "salad_pesto.jpg"},
  {date: "2016-02-15", entree: "Ribs", month: nil, school_id: 1, description: nil, image: "ribs.jpg"},
  {date: "2016-02-11", entree: "Ribs", month: nil, school_id: 2, description: nil, image: "ribs.jpg"},
  {date: "2016-02-20", entree: "Grilled Cheese with Tomato", month: nil, school_id: 1, description: nil, image: "grilled_cheese.jpg"},
  {date: "2016-02-21", entree: "Grilled Cheese with Tomato", month: nil, school_id: 3, description: nil, image: "grilled_cheese.jpg"},
  {date: "2016-01-07", entree: "Pulled Pork Sandwich", month: nil, school_id: 2, description: nil, image: "pulled_pork.jpg"},
  {date: "2016-01-25", entree: "Chicken Pot Pie", month: nil, school_id: 2, description: nil, image: "potpie.jpg"},
  {date: "2016-01-26", entree: "Grilled Cheese with Tomato", month: nil, school_id: 2, description: nil, image: "grilled_cheese.jpg"},
  {date: "2016-01-27", entree: "Beef Stew", month: nil, school_id: 2, description: nil, image: "beef_stew.jpg"},
  {date: "2016-01-28", entree: "BBQ Chicken Sandwich", month: nil, school_id: 1, description: nil, image: "bbq_chicken.jpg"},
  {date: "2016-02-01", entree: "Carnitas Burrito", month: nil, school_id: 2, description: "", image: "burrito.jpg"},
  {date: "2016-02-02", entree: "Ham & Cheese English Muffin", month: nil, school_id: 2, description: nil, image: "ham_cheese.jpg"},
  {date: "2016-02-03", entree: "Chicken Nuggets", month: nil, school_id: 2, description: nil, image: "chicken_nuggets.jpg"},
  {date: "2016-02-04", entree: "Baked Pasta", month: nil, school_id: 2, description: nil, image: "baked_pasta.jpg"},
  {date: "2016-02-08", entree: "Beef Stew", month: nil, school_id: 3, description: nil, image: "beef_stew.jpg"},
  {date: "2016-02-09", entree: "BBQ Chicken Sandwich", month: nil, school_id: 2, description: nil, image: "bbq_chicken.jpg"},
  {date: "2016-02-10", entree: "Pesto Pasta (ASH WEDNESDAY)", month: nil, school_id: 2, description: nil, image: "salad_pesto.jpg"},
  {date: "2016-01-04", entree: "Beef Stew", month: nil, school_id: 4, description: nil, image: "beef_stew.jpg"},
  {date: "2016-01-16", entree: "Ribs", month: nil, school_id: 3, description: nil, image: "ribs.jpg"},
  {date: "2016-01-17", entree: "Pesto Pasta with Garlic Cheese Bread", month: nil, school_id: 3, description: nil, image: "salad_pesto.jpg"},
  {date: "2016-01-18", entree: "Chicken Taco", month: nil, school_id: 3, description: nil, image: "taco.jpg"},
  {date: "2016-01-19", entree: "Baked Pasta", month: nil, school_id: 3, description: nil, image: "baked_pasta.jpg"},
  {date: "2016-01-22", entree: "Chicken Pot Pie", month: nil, school_id: 3, description: nil, image: "potpie.jpg"},
  {date: "2016-02-23", entree: "Chicken Caesar Salad", month: nil, school_id: 3, description: nil, image: "chicken_caesar.jpg"},
  {date: "2016-02-24", entree: "Roast Beef Sandwich", month: nil, school_id: 3, description: nil, image: "roast_beef.jpg"},
  {date: "2016-02-25", entree: "Sloppy Joes", month: nil, school_id: 3, description: nil, image: "sloppy_joes.jpg"},
  {date: "2016-02-29", entree: "Pulled Pork Sandwich", month: nil, school_id: 3, description: nil, image: "pulled_pork.jpg"},
  {date: "2016-01-05", entree: "Chicken Caesar Salad", month: nil, school_id: 4, description: nil, image: "chicken_caesar.jpg"},
  {date: "2016-01-06", entree: "Chicken Nuggets", month: nil, school_id: 4, description: nil, image: "chicken_nuggets.jpg"},
  {date: "2016-01-07", entree: "Grilled Cheese with Tomato", month: nil, school_id: 4, description: nil, image: "grilled_cheese.jpg"},
  {date: "2016-01-11", entree: "Ham & Cheese English Muffin", month: nil, school_id: 4, description: nil, image: "ham_cheese.jpg"},
  {date: "2016-01-12", entree: "Sandwich Wraps", month: nil, school_id: 4, description: nil, image: "wraps.jpg"},
  {date: "2016-01-13", entree: "Roast Beef Sandwich", month: nil, school_id: 4, description: nil, image: "roast_beef.jpg"},
  {date: "2016-02-14", entree: "Carnitas Burrito", month: nil, school_id: 3, description: nil, image: "burrito.jpg"},
  {date: "2016-01-21", entree: "Sloppy Joes", month: nil, school_id: 4, description: nil, image: "sloppy_joes.jpg"},
  {date: "2016-02-01", entree: "Chicken Taco", month: nil, school_id: 4, description: nil, image: "taco.jpg"},
  {date: "2016-02-02", entree: "Pesto Pasta", month: nil, school_id: 4, description: nil, image: "salad_pesto.jpg"},
  {date: "2016-02-03", entree: "Ribs", month: nil, school_id: 4, description: nil, image: "ribs.jpg"},
  {date: "2016-02-24", entree: "Roast Beef Sandwich", month: nil, school_id: 1, description: nil, image: "roast_beef.jpg"},
  {date: "2016-02-04", entree: "Baked Pasta", month: nil, school_id: 4, description: nil, image: "baked_pasta.jpg"},
  {date: "2016-02-08", entree: "Chicken Caesar Salad", month: nil, school_id: 1, description: nil, image: "chicken_caesar.jpg"},
  {date: "2016-02-12", entree: "Carnitas Burrito", month: nil, school_id: 4, description: nil, image: "burrito.jpg"},
  {date: "2016-01-04", entree: "BBQ Chicken Sandwich", month: nil, school_id: 3, description: nil, image: "bbq_chicken.jpg"},
  {date: "2016-02-13", entree: "BBQ Chicken Sandwich", month: nil, school_id: 4, description: nil, image: "bbq_chicken.jpg"},
  {date: "2016-02-28", entree: "Chicken Taco", month: nil, school_id: 2, description: nil, image: "taco.jpg"},
  {date: "2016-01-10", entree: "Roast Beef Sandwich", month: nil, school_id: 2, description: nil, image: "roast_beef.jpg"},
  {date: "2016-01-04", entree: "Chicken Caesar Salad", month: nil, school_id: 2, description: nil, image: "chicken_caesar.jpg"},
  {date: "2016-02-10", entree: "Chicken Pot Pie", month: nil, school_id: 1, description: nil, image: "potpie.jpg"},
  {date: "2016-02-14", entree: "Chicken Pot Pie", month: nil, school_id: 4, description: nil, image: "potpie.jpg"},
  {date: "2016-01-05", entree: "Sloppy Joes", month: nil, school_id: 2, description: nil, image: "sloppy_joes.jpg"},
  {date: "2016-01-05", entree: "Sandwich Wraps", month: nil, school_id: 3, description: nil, image: "wraps.jpg"},
  {date: "2016-01-06", entree: "Sandwich Wraps", month: nil, school_id: 2, description: nil, image: "wraps.jpg"},
  {date: "2016-02-18", entree: "Sandwich Wraps", month: nil, school_id: 1, description: nil, image: "wraps.jpg"},
  {date: "2016-02-02", entree: "Pulled Pork Sandwich", month: nil, school_id: 1, description: nil, image: "pulled_pork.jpg"},
  {date: "2016-02-15", entree: "Pulled Pork Sandwich", month: nil, school_id: 4, description: nil, image: "pulled_pork.jpg"},
  {date: "2016-01-06", entree: "Chicken Nuggets", month: nil, school_id: 3, description: nil, image: "chicken_nuggets.jpg"}
])
Order.create!([
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: "2016-02-02", user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: "2016-02-03", user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: "2016-03-03", user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: "2016-04-01", user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: "2016-04-01", user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: "2016-04-02", user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: "2016-05-02", user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: "2016-05-03", user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: "2016-05-01", user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: "2016-05-02", user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: 4, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: nil, total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: "9.0", total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: nil, subtotal: "9.0", total: nil, date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "4.0", total: "4.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "9.0", total: "9.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.0", subtotal: "13.0", total: "14.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "2.025", subtotal: "22.5", total: "24.525", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.62", subtotal: "18.0", total: "19.62", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "2.835", subtotal: "31.5", total: "34.335", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.62", subtotal: "18.0", total: "19.62", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.62", subtotal: "18.0", total: "19.62", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "3.24", subtotal: "36.0", total: "39.24", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.62", subtotal: "18.0", total: "19.62", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "2.43", subtotal: "27.0", total: "29.43", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "2.43", subtotal: "27.0", total: "29.43", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "2.43", subtotal: "27.0", total: "29.43", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "2.43", subtotal: "27.0", total: "29.43", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.0", subtotal: "0.0", total: "0.0", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "2.025", subtotal: "22.5", total: "24.525", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.62", subtotal: "18.0", total: "19.62", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.62", subtotal: "18.0", total: "19.62", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "2.025", subtotal: "22.5", total: "24.525", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.81", subtotal: "9.0", total: "9.81", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.62", subtotal: "18.0", total: "19.62", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.215", subtotal: "13.5", total: "14.715", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "0.405", subtotal: "4.5", total: "4.905", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil},
  {student_name: nil, price: nil, tax: "1.62", subtotal: "18.0", total: "19.62", date: nil, user_id: nil, email: nil, school_id: nil, school_name: nil, entree: nil}
])
School.create!([
  {name: "Star of the Sea"},
  {name: "St. Monica"},
  {name: "St. Thomas Apostle"},
  {name: "Zion Lutheran"}
])
SchoolLunch.create!([
  {school_id: 1, lunch_id: 1, school_name: "Star", entree: "Chicken Pot Pie", date: nil, month: "January"},
  {school_id: 2, lunch_id: 1, school_name: "St. Monica", entree: "Chicken Pot Pie", date: nil, month: "March"},
  {school_id: 1, lunch_id: 3, school_name: "Star", entree: "Chicken Katsu", date: nil, month: "March"},
  {school_id: 3, lunch_id: 4, school_name: "St. Thomas", entree: "Corn Dog", date: nil, month: "April"}
])
SelectedDay.create!([
  {date: nil, status: nil, user_id: nil, order_id: 26, lunch_id: 10},
  {date: nil, status: nil, user_id: nil, order_id: 26, lunch_id: 11},
  {date: nil, status: nil, user_id: nil, order_id: 27, lunch_id: 10},
  {date: nil, status: nil, user_id: nil, order_id: 27, lunch_id: 11},
  {date: nil, status: nil, user_id: nil, order_id: 28, lunch_id: 10},
  {date: nil, status: nil, user_id: nil, order_id: 28, lunch_id: 11},
  {date: nil, status: nil, user_id: nil, order_id: 29, lunch_id: 6},
  {date: nil, status: nil, user_id: nil, order_id: 29, lunch_id: 7},
  {date: nil, status: nil, user_id: nil, order_id: 29, lunch_id: 8},
  {date: nil, status: nil, user_id: nil, order_id: 30, lunch_id: 10},
  {date: nil, status: nil, user_id: nil, order_id: 30, lunch_id: 11},
  {date: nil, status: nil, user_id: nil, order_id: 31, lunch_id: 2},
  {date: nil, status: nil, user_id: nil, order_id: 32, lunch_id: 10},
  {date: nil, status: nil, user_id: nil, order_id: 32, lunch_id: 11},
  {date: nil, status: nil, user_id: nil, order_id: 33, lunch_id: 10},
  {date: nil, status: nil, user_id: nil, order_id: 33, lunch_id: 11},
  {date: nil, status: nil, user_id: nil, order_id: 34, lunch_id: 10},
  {date: nil, status: nil, user_id: nil, order_id: 35, lunch_id: 10},
  {date: nil, status: nil, user_id: nil, order_id: 35, lunch_id: 11},
  {date: nil, status: nil, user_id: nil, order_id: 36, lunch_id: 10},
  {date: nil, status: nil, user_id: nil, order_id: 36, lunch_id: 11},
  {date: nil, status: nil, user_id: nil, order_id: 36, lunch_id: 12},
  {date: nil, status: nil, user_id: nil, order_id: 37, lunch_id: 6},
  {date: nil, status: nil, user_id: nil, order_id: 37, lunch_id: 7},
  {date: nil, status: nil, user_id: nil, order_id: 37, lunch_id: 8},
  {date: "2016-05-03", status: nil, user_id: nil, order_id: 38, lunch_id: 12},
  {date: "2016-04-03", status: nil, user_id: nil, order_id: 39, lunch_id: 9},
  {date: "2016-05-01", status: nil, user_id: nil, order_id: 39, lunch_id: 10},
  {date: "2016-05-01", status: nil, user_id: nil, order_id: 40, lunch_id: 10},
  {date: "2016-05-02", status: nil, user_id: nil, order_id: 40, lunch_id: 11},
  {date: "2016-02-03", status: nil, user_id: nil, order_id: 41, lunch_id: 3},
  {date: "2016-02-02", status: nil, user_id: nil, order_id: 41, lunch_id: 2},
  {date: "2016-02-03", status: nil, user_id: nil, order_id: 41, lunch_id: 3},
  {date: "2016-01-11", status: "carted", user_id: nil, order_id: 42, lunch_id: 13},
  {date: "2016-01-05", status: nil, user_id: nil, order_id: 43, lunch_id: 23},
  {date: "2016-02-03", status: nil, user_id: nil, order_id: 44, lunch_id: 3},
  {date: "2016-02-02", status: nil, user_id: nil, order_id: 44, lunch_id: 2},
  {date: "2016-02-03", status: nil, user_id: nil, order_id: 45, lunch_id: 3},
  {date: "2016-02-02", status: nil, user_id: nil, order_id: 45, lunch_id: 2},
  {date: "2016-01-05", status: nil, user_id: nil, order_id: 45, lunch_id: 23},
  {date: "2016-01-06", status: nil, user_id: nil, order_id: 45, lunch_id: 24},
  {date: "2016-01-11", status: nil, user_id: nil, order_id: 45, lunch_id: 27},
  {date: "2016-01-08", status: "selected", user_id: nil, order_id: 46, lunch_id: 26},
  {date: "2016-01-12", status: "selected", user_id: nil, order_id: 46, lunch_id: 28},
  {date: "2016-01-15", status: "selected", user_id: nil, order_id: 46, lunch_id: 31},
  {date: "2016-01-19", status: "selected", user_id: nil, order_id: 46, lunch_id: 32},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 47, lunch_id: 22},
  {date: "2016-01-12", status: "selected", user_id: nil, order_id: 48, lunch_id: 28},
  {date: "2016-01-15", status: "selected", user_id: nil, order_id: 49, lunch_id: 31},
  {date: "2016-01-14", status: "selected", user_id: nil, order_id: 50, lunch_id: 30},
  {date: "2016-01-19", status: "selected", user_id: nil, order_id: 50, lunch_id: 32},
  {date: "2016-01-12", status: "selected", user_id: nil, order_id: 50, lunch_id: 28},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 51, lunch_id: 25},
  {date: "2016-01-13", status: "selected", user_id: nil, order_id: 51, lunch_id: 29},
  {date: "2016-01-14", status: "selected", user_id: nil, order_id: 52, lunch_id: 30},
  {date: "2016-01-25", status: "selected", user_id: nil, order_id: 52, lunch_id: 36},
  {date: "2016-01-22", status: "selected", user_id: nil, order_id: 53, lunch_id: 35},
  {date: "2016-01-25", status: "selected", user_id: nil, order_id: 53, lunch_id: 36},
  {date: "2016-01-22", status: "selected", user_id: nil, order_id: 54, lunch_id: 35},
  {date: "2016-01-25", status: "selected", user_id: nil, order_id: 54, lunch_id: 36},
  {date: "2016-01-22", status: "selected", user_id: nil, order_id: 55, lunch_id: 35},
  {date: "2016-01-25", status: "selected", user_id: nil, order_id: 55, lunch_id: 36},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 56, lunch_id: 24},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 56, lunch_id: 25},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 57, lunch_id: 24},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 57, lunch_id: 25},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 68, lunch_id: 23},
  {date: "2016-01-29", status: "selected", user_id: nil, order_id: 74, lunch_id: 40},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 77, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 77, lunch_id: 23},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 77, lunch_id: 24},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 78, lunch_id: 22},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 79, lunch_id: 22},
  {date: "2016-02-15", status: "selected", user_id: nil, order_id: 81, lunch_id: 31},
  {date: "2016-01-12", status: "selected", user_id: nil, order_id: 82, lunch_id: 28},
  {date: "2016-01-13", status: "selected", user_id: nil, order_id: 82, lunch_id: 29},
  {date: "2016-01-12", status: "selected", user_id: nil, order_id: 83, lunch_id: 28},
  {date: "2016-01-12", status: "selected", user_id: nil, order_id: 84, lunch_id: 28},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 85, lunch_id: 22},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 86, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 86, lunch_id: 23},
  {date: "2016-01-17", status: "selected", user_id: nil, order_id: 87, lunch_id: 51},
  {date: "2016-01-18", status: "selected", user_id: nil, order_id: 87, lunch_id: 52},
  {date: "2016-01-12", status: "selected", user_id: nil, order_id: 88, lunch_id: 28},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 89, lunch_id: 22},
  {date: "2016-01-11", status: "selected", user_id: nil, order_id: 89, lunch_id: 27},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 90, lunch_id: 23},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 91, lunch_id: 22},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 93, lunch_id: 22},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 93, lunch_id: 24},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 94, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 94, lunch_id: 23},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 95, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 95, lunch_id: 23},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 95, lunch_id: 24},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 95, lunch_id: 35},
  {date: "2016-01-25", status: "selected", user_id: nil, order_id: 95, lunch_id: 36},
  {date: "2016-01-26", status: "selected", user_id: nil, order_id: 95, lunch_id: 37},
  {date: "2016-01-27", status: "selected", user_id: nil, order_id: 95, lunch_id: 38},
  {date: "2016-02-20", status: "selected", user_id: nil, order_id: 96, lunch_id: 33},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 97, lunch_id: 35},
  {date: "2016-01-25", status: "selected", user_id: nil, order_id: 97, lunch_id: 36},
  {date: "2016-01-26", status: "selected", user_id: nil, order_id: 97, lunch_id: 37},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 98, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 98, lunch_id: 23},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 98, lunch_id: 24},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 98, lunch_id: 25},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 99, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 99, lunch_id: 23},
  {date: "2016-02-02", status: "selected", user_id: nil, order_id: 100, lunch_id: 69},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 101, lunch_id: 48},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 101, lunch_id: 60},
  {date: "2016-01-12", status: "selected", user_id: nil, order_id: 101, lunch_id: 64},
  {date: "2016-01-16", status: "selected", user_id: nil, order_id: 101, lunch_id: 50},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 103, lunch_id: 23},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 103, lunch_id: 24},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 104, lunch_id: 23},
  {date: "2016-02-14", status: "selected", user_id: nil, order_id: 105, lunch_id: 30},
  {date: "2016-02-14", status: "selected", user_id: nil, order_id: 106, lunch_id: 30},
  {date: "2016-02-15", status: "selected", user_id: nil, order_id: 107, lunch_id: 31},
  {date: "2016-02-20", status: "selected", user_id: nil, order_id: 107, lunch_id: 33},
  {date: "2016-02-14", status: "selected", user_id: nil, order_id: 107, lunch_id: 30},
  {date: "2016-02-18", status: "selected", user_id: nil, order_id: 107, lunch_id: 85},
  {date: "2016-02-10", status: "selected", user_id: nil, order_id: 107, lunch_id: 80},
  {date: "2016-02-08", status: "selected", user_id: nil, order_id: 107, lunch_id: 73},
  {date: "2016-02-02", status: "selected", user_id: nil, order_id: 107, lunch_id: 86},
  {date: "2016-02-24", status: "selected", user_id: nil, order_id: 107, lunch_id: 71},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 108, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 108, lunch_id: 23},
  {date: "2016-01-11", status: "selected", user_id: nil, order_id: 108, lunch_id: 27},
  {date: "2016-01-28", status: "selected", user_id: nil, order_id: 108, lunch_id: 39},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 109, lunch_id: 22},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 110, lunch_id: 24},
  {date: "2016-02-21", status: "selected", user_id: nil, order_id: 116, lunch_id: 34},
  {date: "2016-02-24", status: "selected", user_id: nil, order_id: 116, lunch_id: 56},
  {date: "2016-02-01", status: "selected", user_id: nil, order_id: 116, lunch_id: 68},
  {date: "2016-02-02", status: "selected", user_id: nil, order_id: 116, lunch_id: 69},
  {date: "2016-02-14", status: "selected", user_id: nil, order_id: 116, lunch_id: 81},
  {date: "2016-02-01", status: "selected", user_id: nil, order_id: 116, lunch_id: 68},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 117, lunch_id: 24},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 117, lunch_id: 24},
  {date: "2016-02-14", status: "selected", user_id: nil, order_id: 118, lunch_id: 66},
  {date: "2016-02-13", status: "selected", user_id: nil, order_id: 118, lunch_id: 29},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 119, lunch_id: 61},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 119, lunch_id: 62},
  {date: "2016-01-11", status: "selected", user_id: nil, order_id: 119, lunch_id: 63},
  {date: "2016-02-02", status: "selected", user_id: nil, order_id: 119, lunch_id: 69},
  {date: "2016-02-12", status: "selected", user_id: nil, order_id: 119, lunch_id: 74},
  {date: "2016-02-01", status: "selected", user_id: nil, order_id: 119, lunch_id: 68},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 120, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 120, lunch_id: 23},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 121, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 121, lunch_id: 23},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 122, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 123, lunch_id: 23},
  {date: "2016-01-25", status: "selected", user_id: nil, order_id: 124, lunch_id: 36},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 124, lunch_id: 35},
  {date: "2016-01-26", status: "selected", user_id: nil, order_id: 124, lunch_id: 37},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 125, lunch_id: 23},
  {date: "2016-02-14", status: "selected", user_id: nil, order_id: 126, lunch_id: 30},
  {date: "2016-02-20", status: "selected", user_id: nil, order_id: 127, lunch_id: 33},
  {date: "2016-02-24", status: "selected", user_id: nil, order_id: 127, lunch_id: 71},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 133, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 143, lunch_id: 23},
  {date: "2016-01-08", status: "selected", user_id: nil, order_id: 143, lunch_id: 26},
  {date: "2016-01-11", status: "selected", user_id: nil, order_id: 143, lunch_id: 27},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 147, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 148, lunch_id: 23},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 148, lunch_id: 24},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 149, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 149, lunch_id: 23},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 150, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 150, lunch_id: 23},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 150, lunch_id: 24},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 151, lunch_id: 24},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 151, lunch_id: 25},
  {date: "2016-01-12", status: "selected", user_id: nil, order_id: 151, lunch_id: 28},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 152, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 152, lunch_id: 23},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 154, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 155, lunch_id: 23},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 158, lunch_id: 22},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 159, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 160, lunch_id: 23},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 161, lunch_id: 22},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 163, lunch_id: 25},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 163, lunch_id: 24},
  {date: "2016-01-08", status: "selected", user_id: nil, order_id: 164, lunch_id: 26},
  {date: "2016-01-11", status: "selected", user_id: nil, order_id: 164, lunch_id: 27},
  {date: "2016-01-28", status: "selected", user_id: nil, order_id: 164, lunch_id: 39},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 165, lunch_id: 35},
  {date: "2016-01-10", status: "selected", user_id: nil, order_id: 165, lunch_id: 78},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 165, lunch_id: 79},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 166, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 166, lunch_id: 23},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 166, lunch_id: 24},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 166, lunch_id: 25},
  {date: "2016-01-28", status: "selected", user_id: nil, order_id: 166, lunch_id: 39},
  {date: "2016-01-12", status: "selected", user_id: nil, order_id: 166, lunch_id: 28},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 167, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 167, lunch_id: 23},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 167, lunch_id: 24},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 167, lunch_id: 25},
  {date: "2016-01-11", status: "selected", user_id: nil, order_id: 167, lunch_id: 27},
  {date: "2016-01-12", status: "selected", user_id: nil, order_id: 167, lunch_id: 28},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 168, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 168, lunch_id: 23},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 169, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 169, lunch_id: 23},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 170, lunch_id: 23},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 171, lunch_id: 22},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 172, lunch_id: 22},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 173, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 173, lunch_id: 23},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 175, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 175, lunch_id: 23},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 175, lunch_id: 24},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 176, lunch_id: 23},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 177, lunch_id: 22},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 178, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 178, lunch_id: 23},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 179, lunch_id: 23},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 180, lunch_id: 23},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 180, lunch_id: 24},
  {date: "2016-01-11", status: "selected", user_id: nil, order_id: 180, lunch_id: 27},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 182, lunch_id: 22},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 182, lunch_id: 23},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 183, lunch_id: 24},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 183, lunch_id: 23},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 184, lunch_id: 79},
  {date: "2016-02-21", status: "selected", user_id: nil, order_id: 185, lunch_id: 34},
  {date: "2016-02-13", status: "selected", user_id: nil, order_id: 185, lunch_id: 29},
  {date: "2016-02-02", status: "selected", user_id: nil, order_id: 185, lunch_id: 69},
  {date: "2016-02-01", status: "selected", user_id: nil, order_id: 185, lunch_id: 68},
  {date: "2016-02-21", status: "selected", user_id: nil, order_id: 185, lunch_id: 34},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 186, lunch_id: 48},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 187, lunch_id: 61},
  {date: "2016-01-13", status: "selected", user_id: nil, order_id: 187, lunch_id: 65},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 188, lunch_id: 60},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 188, lunch_id: 60},
  {date: "2016-02-02", status: "selected", user_id: nil, order_id: 188, lunch_id: 69},
  {date: "2016-02-13", status: "selected", user_id: nil, order_id: 188, lunch_id: 29},
  {date: "2016-02-13", status: "selected", user_id: nil, order_id: 189, lunch_id: 29},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 189, lunch_id: 60},
  {date: "2016-01-16", status: "selected", user_id: nil, order_id: 190, lunch_id: 50},
  {date: "2016-01-18", status: "selected", user_id: nil, order_id: 190, lunch_id: 52},
  {date: "2016-02-02", status: "selected", user_id: nil, order_id: 190, lunch_id: 69},
  {date: "2016-02-01", status: "selected", user_id: nil, order_id: 190, lunch_id: 68},
  {date: "2016-01-18", status: "selected", user_id: nil, order_id: 191, lunch_id: 52},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 191, lunch_id: 75},
  {date: "2016-01-16", status: "selected", user_id: nil, order_id: 191, lunch_id: 50},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 192, lunch_id: 60},
  {date: "2016-02-13", status: "selected", user_id: nil, order_id: 192, lunch_id: 29},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 193, lunch_id: 60},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 193, lunch_id: 48},
  {date: "2016-01-16", status: "selected", user_id: nil, order_id: 193, lunch_id: 50},
  {date: "2016-01-16", status: "selected", user_id: nil, order_id: 194, lunch_id: 50},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 194, lunch_id: 48},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 195, lunch_id: 60},
  {date: "2016-01-04", status: "selected", user_id: nil, order_id: 195, lunch_id: 48},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 195, lunch_id: 61},
  {date: "2016-01-16", status: "selected", user_id: nil, order_id: 195, lunch_id: 50},
  {date: "2016-01-18", status: "selected", user_id: nil, order_id: 195, lunch_id: 52},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 196, lunch_id: 60},
  {date: "2016-01-16", status: "selected", user_id: nil, order_id: 196, lunch_id: 50},
  {date: "2016-02-02", status: "selected", user_id: nil, order_id: 197, lunch_id: 69},
  {date: "2016-02-01", status: "selected", user_id: nil, order_id: 197, lunch_id: 68},
  {date: "2016-02-21", status: "selected", user_id: nil, order_id: 197, lunch_id: 34},
  {date: "2016-02-08", status: "selected", user_id: nil, order_id: 197, lunch_id: 45},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 198, lunch_id: 60},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 198, lunch_id: 61},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 198, lunch_id: 62},
  {date: "2016-02-13", status: "selected", user_id: nil, order_id: 199, lunch_id: 29},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 199, lunch_id: 83},
  {date: "2016-01-22", status: "selected", user_id: nil, order_id: 199, lunch_id: 54},
  {date: "2016-01-22", status: "selected", user_id: nil, order_id: 200, lunch_id: 54},
  {date: "2016-01-05", status: "selected", user_id: nil, order_id: 201, lunch_id: 23},
  {date: "2016-01-06", status: "selected", user_id: nil, order_id: 201, lunch_id: 24},
  {date: "2016-01-07", status: "selected", user_id: nil, order_id: 201, lunch_id: 25},
  {date: "2016-01-08", status: "selected", user_id: nil, order_id: 201, lunch_id: 26}
])
Student.create!([
  {student_name: "Kevin Jung", grade: 3, user_id: 1, school_id: 1},
  {student_name: "Stacey Jung", grade: 8, user_id: 1, school_id: 2},
  {student_name: "Anthony Wu", grade: 2, user_id: 3, school_id: 3},
  {student_name: "Natasha Wu", grade: 4, user_id: 3, school_id: 4}
])
StudentSchool.create!([
  {school_id: 1, student_id: 1},
  {school_id: 2, student_id: 2}
])
StudentUser.create!([
  {student_id: 2, user_id: 1},
  {student_id: 1, user_id: 1},
  {student_id: 3, user_id: 2}
])
